# Generated by Django 4.0.5 on 2022-07-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_agent_age_alter_agent_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/profileImages/'),
        ),
    ]
